[log]
level = "Info"
dir = "__PRIMARY_LOG_DIR__"

[[database]]
db = "__PRIMARY_DB__"
cache_root = "__PRIMARY_CACHE__"
monitor_interval_ms = 50
checkpoint_interval_secs = 1
wal_retention_count = 20
apply_checkpoint_frame_interval = 20
apply_checkpoint_interval_ms = 200

[[database.replicate]]
name = "stream-primary"
[database.replicate.params]
type = "stream"
addr = "http://0.0.0.0:50051"
