FROM rust:1.83-bookworm as builder
WORKDIR /app
COPY . .
RUN apt-get update && apt-get install -y protobuf-compiler
RUN cargo build --release --features storage

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y ca-certificates sqlite3 curl && rm -rf /var/lib/apt/lists/*
COPY --from=builder /app/target/release/replited /usr/local/bin/replited
RUN chmod +x /usr/local/bin/replited
ENTRYPOINT ["/usr/local/bin/replited"]
