FROM rust:1.88-bookworm as builder
WORKDIR /app
COPY . .
RUN apt-get update && apt-get install -y protobuf-compiler musl-tools file
RUN rustup target add x86_64-unknown-linux-musl
RUN cargo build --release --features storage --target x86_64-unknown-linux-musl
RUN file /app/target/x86_64-unknown-linux-musl/release/replited \
    | grep -Eq 'statically linked|static-pie linked'

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y ca-certificates sqlite3 curl && rm -rf /var/lib/apt/lists/*
COPY --from=builder /app/target/x86_64-unknown-linux-musl/release/replited /usr/local/bin/replited
RUN chmod +x /usr/local/bin/replited
RUN /usr/local/bin/replited --version
ENTRYPOINT ["/usr/local/bin/replited"]
