# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import replication_pb2 as replication__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in replication_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReplicationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamWal = channel.unary_stream(
                '/replication.Replication/StreamWal',
                request_serializer=replication__pb2.Handshake.SerializeToString,
                response_deserializer=replication__pb2.WalPacket.FromString,
                _registered_method=True)
        self.GetRestoreConfig = channel.unary_unary(
                '/replication.Replication/GetRestoreConfig',
                request_serializer=replication__pb2.RestoreRequest.SerializeToString,
                response_deserializer=replication__pb2.RestoreConfig.FromString,
                _registered_method=True)


class ReplicationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamWal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRestoreConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplicationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamWal': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamWal,
                    request_deserializer=replication__pb2.Handshake.FromString,
                    response_serializer=replication__pb2.WalPacket.SerializeToString,
            ),
            'GetRestoreConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRestoreConfig,
                    request_deserializer=replication__pb2.RestoreRequest.FromString,
                    response_serializer=replication__pb2.RestoreConfig.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'replication.Replication', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('replication.Replication', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Replication(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamWal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/replication.Replication/StreamWal',
            replication__pb2.Handshake.SerializeToString,
            replication__pb2.WalPacket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRestoreConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.Replication/GetRestoreConfig',
            replication__pb2.RestoreRequest.SerializeToString,
            replication__pb2.RestoreConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
