# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: replication.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'replication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11replication.proto\x12\x0breplication\"!\n\x0eRestoreRequest\x12\x0f\n\x07\x64\x62_name\x18\x01 \x01(\t\"$\n\rRestoreConfig\x12\x13\n\x0b\x63onfig_json\x18\x01 \x01(\t\"V\n\tWalPacket\x12\x14\n\nframe_data\x18\x01 \x01(\x0cH\x00\x12(\n\x05\x65vent\x18\x02 \x01(\x0b\x32\x17.replication.CheckpointH\x00\x42\t\n\x07payload\"O\n\tHandshake\x12\x0f\n\x07\x64\x62_name\x18\x01 \x01(\t\x12\x12\n\ngeneration\x18\x02 \x01(\t\x12\x0e\n\x06offset\x18\x03 \x01(\x04\x12\r\n\x05index\x18\x04 \x01(\x04\"\x1b\n\nCheckpoint\x12\r\n\x05index\x18\x01 \x01(\r\"\x16\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x99\x01\n\x0bReplication\x12=\n\tStreamWal\x12\x16.replication.Handshake\x1a\x16.replication.WalPacket0\x01\x12K\n\x10GetRestoreConfig\x12\x1b.replication.RestoreRequest\x1a\x1a.replication.RestoreConfigb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'replication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESTOREREQUEST']._serialized_start=34
  _globals['_RESTOREREQUEST']._serialized_end=67
  _globals['_RESTORECONFIG']._serialized_start=69
  _globals['_RESTORECONFIG']._serialized_end=105
  _globals['_WALPACKET']._serialized_start=107
  _globals['_WALPACKET']._serialized_end=193
  _globals['_HANDSHAKE']._serialized_start=195
  _globals['_HANDSHAKE']._serialized_end=274
  _globals['_CHECKPOINT']._serialized_start=276
  _globals['_CHECKPOINT']._serialized_end=303
  _globals['_ACK']._serialized_start=305
  _globals['_ACK']._serialized_end=327
  _globals['_REPLICATION']._serialized_start=330
  _globals['_REPLICATION']._serialized_end=483
# @@protoc_insertion_point(module_scope)
