name: Unit Test

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-24.04
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v4
        with:
          # fetch depth set to 0 to make sure we have correct diff result.
          fetch-depth: 0

      - name: Setup Rust toolchain
        uses: ./.github/actions/setup

      - name: 'Run clippy (non-blocking)'
        continue-on-error: true
        shell: bash
        run: |
          cargo clippy --all-targets

      - name: 'Run Unit tests'
        shell: bash
        run: |
          cargo test
